sudo: required
language: C

matrix:
  include:
    - os: osx
    - os: linux
      dist: trusty
      compiler: gcc-5
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-5
            - p7zip-full

install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update; brew install dmd rust p7zip; fi
  - echo $CI

script:
  - scripts/get.sh __local__
  - source ~/.xmake/profile
  - xmake --version
  - xmake -P core 
  - export XMAKE_PROGRAM_DIR=$PWD/xmake
  - core/build/xmake --version
  - export XMAKE_PROGRAM_DIR=~/.local/share/xmake
  - cp core/build/xmake "$XMAKE_PROGRAM_DIR" || sudo cp core/build/xmake "$XMAKE_PROGRAM_DIR"
  - xmake --version
  - xmake l private.utils.bcsave --rootname='@programdir' -x 'scripts/**|templates/**' xmake
  - xmake --version
  - travis_wait 60 xmake lua -v -D tests/run.lua
  - scripts/archive-all
  - scripts/makeself/build-runfile.sh 
  - scripts/makeself/xmake.gz.run --info
