name: build

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v1
    - uses: xmake-io/github-action-setup-xmake@v1
      with:
        xmake-version: branch@dev
    - uses: mihails-strasuns/setup-dlang@v0.5.0
      with:
        compiler: dmd-latest
    - name: tests
      run: |
        xmake lua -v -D tests/run.lua
